name: "Register an event on PipeCD"
on:
  push:
    branches:
    - master
jobs:
  register-event:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: echo "TAG=`git describe --tags`" >> $GITHUB_ENV
    - uses: pipe-cd/actions-event-register@v1
      with:
        api-address: ${{ secrets.PIPECD_API_ADDRESS }}
        api-key: ${{ secrets.PIPECD_API_KEY }}
        event-name: image-update
        labels: app=foo,env=dev
        data: ${{ env.TAG }}
